/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'category' : string,
}
export interface AnnouncementInput {
  'title' : string,
  'body' : string,
  'category' : string,
}
export interface Event {
  'id' : bigint,
  'organizer' : Principal,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'location' : string,
}
export interface EventInput {
  'title' : string,
  'date' : bigint,
  'description' : string,
  'location' : string,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'role' : UserRole,
  'department' : string,
}
export type UserRole = { 'staff' : null } |
  { 'faculty' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createAnnouncement' : ActorMethod<[AnnouncementInput], bigint>,
  'createEvent' : ActorMethod<[EventInput], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAnnouncement' : ActorMethod<[bigint], [] | [Announcement]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getEvent' : ActorMethod<[bigint], [] | [Event]>,
  'getMyRole' : ActorMethod<[], UserRole__1>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];